---
version: "2"

services:
  proxy:
    volumes:
      - /data/nginx_config:/etc/nginx
      - /data/nginx_releasenote:/usr/share/nginx/html

  ldap:
    volumes:
      - /data/ldap_db:/var/lib/ldap
      - /data/ldap_static:/etc/ldap
      - /data/ldap_slapd:/var/lib/slapd
      - /data/ldap_certs:/etc/ssl/certs
      - /data/ldap_export:/tmp

  gitlab:
    volumes:
      - /data/gitlab_conf:/etc/gitlab
      - /data/gitlab_logs:/var/log/gitlab
      - /data/gitlab_data:/var/opt/gitlab

  sensu-api:
    volumes:
      - /data/sensu_api_conf:/etc/sensu/conf.d

  sensu-server:
    volumes:
      - /data/sensu_server_conf:/etc/sensu/conf.d

  sensu-client:
    volumes:
      - /data/sensu_client_conf:/etc/sensu/conf.d

  sensu-rabbitmq:
    volumes:
      - /data/sensu_rabbitmq_data:/var/lib/rabbitmq

  sensu-redis:
    volumes:
      - /data/sensu_redis_data:/data

  sonar-mysql:
    volumes:
      - /data/sonar_mysql_data:/var/lib/mysql 

  sonar:
    volumes:
      - /data/sonar_data:/opt/sonarqube/data
      - /data/sonar_extensions:/opt/sonarqube/extensions
      - /data/sonar_logs:/opt/sonarqube/logs

  jenkins:
    user: root 
    volumes:
      - /data/jenkins_home:/var/jenkins_home 

  selenium-node-chrome:
    volumes:
      - /data/selenium_config:/var/selenium-config

  selenium-node-firefox:
    volumes:
      - /data/selenium_config:/var/selenium-config

  nexus:
    volumes:
      - /data/nexus_sonatype_work:/sonatype-work
